#:schema node_modules/wrangler/config-schema.json
name = "mindvex"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

# Environment Variables for Production
[vars]
VITE_BACKEND_URL = "https://mindvex-backend.onrender.com/api"
